### ISSUE TITLE
Wrong link to agreement-PDF?

### ISSUE THREAD

**Issue by StePerBo** [neurobin/letsacme#3]
Hi,

I tried to request a certificate, but always got Error 400.
I saw that the link to the agreement-PDF is not the right one. After changing it to https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf , I get the cert.
Did I load an old code?

**Comment by neurobin** [comment]
The latest version of letsacme was 0.0.5.

``` sh
python letsacme.py --version
```

and it contained the old agreement link. Updated in 0.0.6.

Thanks a lot, for reporting this... :+1:

**Comment by neurobin** [comment]
But you should wait for 0.0.7 version. The agreement URL will be retrieved automatically rather than hard coded.

**Comment by neurobin** [comment]
Fixed in v0.0.7
